Algoritmo "Antecessor"
// Disciplina : [Lógica de Programação e JavaScript]
// Professor : Jailson Costa dos Santos
// Descrição : Pedir um número e mostrar o antecessor
// Autor(a) : Juliane <3
// Data atual : 25/08/2021
Var
// Seção de Declarações das variáveis
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Bom dia!!!")
Escreval("Digite um número:")
Leia(numero)
Escreval("O antecessor do número é:", numero-1)
Fimalgoritmo